name: pujapurohit
description: Puja Purohit is an online service aggregator wherein customers may select from a wide variety of Pujas such as , satyanarayan puja, griha pravesh , marriage ceremony, engagement ceremony, Laxmi puja , Ganesha puja and Durga puja, mata ki chouki and jaagran, maha mritunjya jap, havans,naming ceremony, mundan ceremony, birthday ceremony,last rite rituals and many others. Puja Purohit shall connect customers seeking such services with the relevant Pandit chosen by customer itself, who shall provide the services at the customer’s doorstep/venue of choice. Puja Purohit aims to serve you for your exact and customised religious need with our well experienced Purohit'ss and puja samagri at reasonable prices and hassle free service. Customers can book Purohit online. On completion of the service, the Customers may provide us with reviews and feedbacks for the Service Provider.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^5.0.0
  google_fonts: ^2.2.0
  # google_fonts: ^2.0.0
  get: ^4.1.3
  responsive_framework: ^0.1.0
  auto_size_text: ^3.0.0-nullsafety.0
  carousel_slider: ^4.0.0-nullsafety.0
  animated_text_kit: ^4.1.1
  geolocator: ^7.1.0
  firebase_auth: ^3.1.1
  firebase_core: ^1.6.0
  cloud_firestore: ^2.5.3
  cloud_firestore_web: ^2.4.2
  firebase_messaging: ^10.0.3
  firebase_messaging_web: ^2.0.2
  otp_text_field: ^1.1.0
  line_icons: ^2.0.1
  geoflutterfire: ^3.0.0-nullsafety.4
  google_maps_flutter_web: ^0.3.0
  google_maps_flutter: ^2.0.3
  http: ^0.13.3
  flip_card: ^0.5.0
  sliver_tools: ^0.2.2
  uuid: ^3.0.4
  otp: ^3.0.0-nullsafety.0
  intl: ^0.17.0
  flutter_rounded_date_picker: ^2.0.2
  percent_indicator: ^3.3.0-nullsafety.1
  url_launcher: ^6.0.4
  flutter_switch: ^0.3.1
  flare_flutter: ^3.0.1
  flutter_slidable: ^0.6.0
  dotted_line: ^3.0.0
  universal_html: ^2.0.8
  youtube_player_iframe: ^2.1.0
  flutter_google_places_web: ^1.0.0
  country_icons: ^2.0.2
  image_picker: ^0.8.3+2
  image_picker_web: ^2.0.3+1
  video_player: ^2.1.4
  flutter_image_slideshow: ^0.1.1
  flutter_countdown_timer: ^4.1.0
  firebase_storage: ^10.0.2
  places_service:
  hovering: ^1.0.4
  scroll_to_index: ^2.0.0
  #uuid: ^3.0.5
  #http: ^0.13.4
  
  flutter_staggered_grid_view: ^0.4.0
  wc_flutter_share: ^0.4.0
  image_gallery_saver: ^1.6.9
  share_plus: ^3.0.0
  js: ^0.6.3
  dio: ^4.0.0
  #flutter_image_slideshow: ^0.1.2
  #flutter_google_places: ^0.3.0
  
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0
  build_runner: ^1.10.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/payment.html
    - assets/test.html
    - assets/images/1.png
    - assets/images/astro.png
    - assets/images/pandit.png
    - assets/images/logo.png
    - assets/images/location.png
    - assets/images/loader_floating.flr
    - assets/images/signin2.png
    - assets/images/scooter.png
    - assets/images/google-play-badge.png
    - assets/mark.png
    - assets/images/lap.jpg
    - assets/images/person1.jpg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
